<?php
// $Id: contact_information.module $

function contact_information_node_view($node, $view_mode) {
  if ($node->type == 'contact_information' && $view_mode == 'full' && node_is_page($node)) {
    drupal_goto('node/' . $node->field_ci_patient['und'][0]['nid'] . '/contact-info');
  }  

  return $node;
}

function contact_information_form_contact_information_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type']) && isset($form['#node'])) {
    if ('contact_information_node_form' == $form_id) {
      $form['title']['#access'] = FALSE;
      $form['field_ci_patient']['#access'] = FALSE;

      $form['group_audience']['#access'] = FALSE;
      $form['group_content_access']['#access'] = FALSE;
    }
  }
}
