<?php
// $Id: skeletome_util.module $

define('__EDITOR_ROLE__', 'editor');
define('__FORUMADMIN_ROLE__', 'forumadmin');
define('__SUPERADMIN_ROLE__', 'admin');

function skeletome_util_init() {
  module_load_include('inc', 'skeletome_util', 'skeletome_biblio');
}

function skeletome_util_menu() {

  $items['skeletome-util/get-phenotype'] = array(
    'title' => 'Get phenotype',
    'page callback' => 'get_phenotype_callback',
    'type' => MENU_CALLBACK,
    'file' => 'skeletome_biblio.inc',
    'access callback' => TRUE,
  );

  $items['skeletome-util/get-biblio'] = array(
    'title' => 'Get biblio',
    'page callback' => 'get_biblio_callback',
    'type' => MENU_CALLBACK,
    'file' => 'skeletome_biblio.inc',
    'access callback' => TRUE,
  );

  $items['node/%node/citations'] = array(
    'title' => 'Citations',
    'page callback' => 'biblio_citations_callback',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'biblio_citations.inc',
    'access callback' 	=> 'validate_biblio_cite_callback',
    'access arguments' 	=> array(1, 'biblio'),
    'weight' => 2,
  );

  $items['node/%node/biblio/pheno_citation/delete/%/%/%/%'] = array(
    'title' => 'Delete pheno citation',
    'page callback' => 'delete_pheno_biblio_citation_callback',
    'page arguments' => array(5, 6, 7, 8),
    'type' => MENU_CALLBACK,
    'file' => 'biblio_citations.inc',
    'access callback' => TRUE,
  );

  $items['node/%node/biblio/gm_citation/delete/%/%'] = array(
    'title' => 'Delete gm citation',
    'page callback' => 'delete_gm_biblio_citation_callback',
    'page arguments' => array(5, 6),
    'type' => MENU_CALLBACK,
    'file' => 'biblio_citations.inc',
    'access callback' => TRUE,
  );

  return $items;
}

function validate_biblio_cite_callback($node) {
  if ($node->type === 'biblio') {
    if (array_key_exists('und', $node->field_biblio_ssc_field)) {
      if (!empty($node->field_biblio_ssc_field['und'])) {
	return TRUE;
      }
    }
  }

  return FALSE;
}

function is_current_user_editor() {
  global $user;
  return in_array(__EDITOR_ROLE__, $user->roles);
}

function is_current_user_forumadmin() {
  global $user;
  return in_array(__FORUMADMIN_ROLE__, $user->roles);
}

function is_current_user_superadmin() {
  global $user;
  return in_array(__SUPERADMIN_ROLE__, $user->roles);
}

function is_node_of_type($node, $type) {
  return $node->type === $type;
}

function get_nodes_of_type($type) {
  $nodes = array();
  $sql = 'SELECT nid, title FROM {node} n WHERE n.type = :type';
  $result = db_query($sql, array(':type' => $type));
  foreach ($result as $row) {
    $nodes[$row->nid] = $row->title;
  }

  return $nodes;
}

function get_nodes_with_tag($tid) {
  $nids = array();
  $sql = 'SELECT nid FROM {taxonomy_index} ti WHERE ti.tid = :tid';
  $result = db_query($sql, array(':tid' => $tid));
  foreach ($result as $row) {
    $nids[$row->nid] = $row->nid;
  }

  return $nids;
}

function get_scc_for_phenotid($pheno_tid) {
  $scc_nids = array();
  $sql = 'SELECT entity_id, field_ssc_phenoterm_tid FROM {field_data_field_ssc_phenoterm} WHERE field_ssc_phenoterm_tid = :pheno_tid';
  $result = db_query($sql, array(':pheno_tid' => $pheno_tid));
  foreach ($result as $row) {
    $scc_nids[] = $row->entity_id;
  }
  return $scc_nids;
}

function get_scc_for_bd($bd_nid) {
  $scc_nids = array();
  $sql = 'SELECT entity_id, field_ssc_bonedysplasia_nid FROM {field_data_field_ssc_bonedysplasia} WHERE field_ssc_bonedysplasia_nid = :bd_nid';
  $result = db_query($sql, array(':bd_nid' => $bd_nid));
  foreach ($result as $row) {
    $scc_nids[] = $row->entity_id;
  }
  return $scc_nids;
}

function count_nodes($node_type) {
  $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
  $result = db_query($sql, array(':type' => $node_type));

  $count = 0;
  foreach ($result as $row) {
    $count++;
  }

  return $count;
}

function count_users() {
  $sql = 'SELECT uid FROM {users} u';
  $result = db_query($sql, array());

  $count = 0;
  foreach ($result as $row) {
    $count++;
  }

  return ($count - 1);
}

function count_tags($vocab_name) {
  $sql = 'SELECT vid FROM {taxonomy_vocabulary} tv WHERE tv.machine_name = :vocab_name';
  $result = db_query($sql, array(':vocab_name' => $vocab_name));

  $vid = -1;
  foreach ($result as $row) {
    $vid = $row->vid;
  }

  $sql = 'SELECT vid FROM {taxonomy_term_data} ttd WHERE ttd.vid = :vid';
  $result = db_query($sql, array(':vid' => $vid));
  $count = 0;
  foreach ($result as $row) {
    $count++;
  }

  return $count;
}

function get_vid_for_vocabulary($machine_name) {
  $sql = 'SELECT vid, machine_name FROM {taxonomy_vocabulary} tv WHERE tv.machine_name = :voc_name';
  $result = db_query($sql, array(':voc_name' => $machine_name));
  foreach ($result as $r) {
    return $r->vid;
  }

  return NULL;
}

function remove_from_array($node, $field, $index, $needle, $is_node) {
  $to_keep = array();
  $und_array = $node->$field;

  foreach ($und_array['und'] as $item) {
    if ($item[$index] != $needle) {
      $to_keep[] = $item;
    }
  }

  $und_array['und'] = $to_keep;
  $node->$field = $und_array;
  if ($is_node) {
    node_save($node);
  } else {
    taxonomy_term_save($node);
  }
}
