<?php
// $Id: skeletome_config.module $

define('_IMPORT_VIEWS_', 'edit-configuration-import-views');
define('_GROUPCONTENT_MANAGEMENT_', 'edit-configuration-manage-groupcontent');
define('_GENERAL_MANAGEMENT_', 'edit-configuration-manage-general');
define('_DELETE_CONTENT_', 'edit-configuration-delete-content');

function skeletome_config_init() {
  module_load_include('inc', 'skeletome_config', 'includes/import_views');
  module_load_include('inc', 'skeletome_config', 'includes/manage_groupcontent');
  module_load_include('inc', 'skeletome_config', 'includes/manage_general');
  module_load_include('inc', 'skeletome_config', 'includes/delete_content');
}

function skeletome_config_menu() {
  $items['admin/config/system/skeletome_configuration'] = array(
    'title' => 'SKELETOME Configuration',
    'description' => 'Configuration of the SKELETOME content.',
    'page callback' => 'skeletome_config_page',
    'access arguments' => array('administer content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function skeletome_config_page() {
  return drupal_get_form('skeletome_config_form');
}

function skeletome_config_form() {
  $form['#attributes'] = array('enctype' => "multipart/form-data");

  $form['configuration'] = array(
    '#type' => 'vertical_tabs',
    '#title' => t('Configuration'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );

  $form['configuration']['import_views'] = array(
    '#type' => 'fieldset',
    '#title' => t('Import views'),
    '#weight' => 1,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    'value' => import_views_form(),
  );

  $form['configuration']['manage_groupcontent'] = array(
    '#type' => 'fieldset',
    '#title' => t('Group content management'),
    '#weight' => 2,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    'value' => manage_groupcontent_form(),
  );

  $form['configuration']['manage_general'] = array(
    '#type' => 'fieldset',
    '#title' => t('General management'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    'value' => manage_general_form(),
  );

  $form['configuration']['delete_content'] = array(
    '#type' => 'fieldset',
    '#title' => t('Clear content'),
    '#weight' => 4,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    'value' => delete_content_form(),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;
}

function import_views_form() {
  $views_location_form = array();
  $views_location_form['#attributes'] = array('enctype' => "multipart/form-data");

  $views_location_form['view_file'] = array(
    '#type' => 'textfield',
    '#title' => t('View file'),
    '#description' => t('Input the view file to be imported.'),
  );

  $options = array();
  $options['-1'] = '- Select -';
  $options['sidebar_first'] = 'Sidebar';
  $options['content'] = 'Main content';

  $views_location_form['region'] = array(
    '#type' => 'select',
    '#title' => t('Region'),
    '#description' => t("Choose the region where the view's block will be placed."),
    '#options' => $options,
  );

  $options = array();
  $options['-1'] = '- Select -';
  $sql = 'SELECT type, name FROM {node_type}';
  $result = db_query($sql, array());
  foreach ($result as $row) {
    $options[$row->type] = $row->name;
  }

  $views_location_form['content_type'] = array(
    '#type' => 'select',
    '#title' => t('Content type'),
    '#description' => t('Choose the content type to which the presence of the block will be restricted.'),
    '#options' => $options,
  );

  $options = array();
  $options['-1'] = '- Select -';
  $options['0'] = 'Authenticated users';

  $views_location_form['user_restriction'] = array(
    '#type' => 'select',
    '#title' => t('Users'),
    '#description' => t('Choose the user restrictions to be applied on the block.'),
    '#options' => $options,
  );

  return $views_location_form;
}

function manage_groupcontent_form() {
  $groupcontent_form = array();

  $options = array();
  $options['-1'] = '- Select -';
  $options['0'] = 'Set group content types';
  $options['1'] = 'Add access control restrictions';

  $groupcontent_form['management'] = array(
    '#type' => 'select',
    '#title' => t('Group content management ...'),
    '#description' => t('Choose group content management action.'),
    '#options' => $options,
  );

  return $groupcontent_form;
}

function manage_general_form() {
  $generalmanagement_form = array();

  $options = array();
  $options['-1'] = '- Select -';
  $options['0'] = 'Create user roles';
  $options['1'] = 'Add general access control restrictions';
  $options['2'] = 'Add missing fields to content types';
  $options['3'] = 'Create patient views pages';

  $generalmanagement_form['management'] = array(
    '#type' => 'select',
    '#title' => t('General management ...'),
    '#description' => t('Choose general management action.'),
    '#options' => $options,
  );

  return $generalmanagement_form;
}

function delete_content_form() {
  $delete_form = array();

  $options = array();
  $options['-1'] = '- Select -';
  $options['0'] = 'Bone Dysplasias';
  $options['1'] = 'Genes and gene mutations';
  $options['2'] = 'Gene mutation types';
  $options['3'] = 'Everything';
  $options['4'] = 'Mode of inheritance vocabulary';
  $options['5'] = 'SKELETOME vocabulary';

  $delete_form['to_delete'] = array(
    '#type' => 'select',
    '#title' => t('Clear ...'),
    '#description' => t('Choose the type of data to be cleared.'),
    '#options' => $options,
  );

  return $delete_form;
}

function skeletome_config_form_submit($form, &$form_state) {
  $active_tab = $form_state['input']['configuration']['configuration__active_tab'];

  if ($active_tab === _IMPORT_VIEWS_) {
    $view_file = $form_state['values']['configuration']['import_views']['value']['view_file'];
    if ($view_file !== '') {
      $region = $form_state['values']['configuration']['import_views']['value']['region'];
      $content_restriction = $form_state['values']['configuration']['import_views']['value']['content_type'];
      $user_restriction = $form_state['values']['configuration']['import_views']['value']['user_restriction'];

      if ($content_restriction === '-1') {
	$content_restriction = NULL;
      }
      if ($user_restriction === '-1') {
	$user_restriction = NULL;
      } else {
	$user_restriction = 2;
      }
      import_view($view_file, $region, $content_restriction, $user_restriction);
    } else {
      drupal_set_message('Please enter a valid view file.', 'error');
    }
  }
  if ($active_tab === _GROUPCONTENT_MANAGEMENT_) {
    $action = $form_state['values']['configuration']['manage_groupcontent']['value']['management'];
      if ($action !== '-1') {
	perform_gcm_action($action);
      } else {
	drupal_set_message('Please select a valid content type to be deleted.', 'error');
      }
  }
  if ($active_tab === _GENERAL_MANAGEMENT_) {
    $action = $form_state['values']['configuration']['manage_general']['value']['management'];
      if ($action !== '-1') {
	perform_gm_action($action);
      } else {
	drupal_set_message('Please select a valid content type to be deleted.', 'error');
      }
  }
  if ($active_tab === _DELETE_CONTENT_) {
    $to_delete = $form_state['values']['configuration']['delete_content']['value']['to_delete'];
      if ($to_delete !== '-1') {
	delete_content($to_delete);
      } else {
	drupal_set_message('Please select a valid content type to be deleted.', 'error');
      }
  }

  return $form;
}
