<?php
// $Id: gene.install $

function gene_install() {
  $t = get_t();

  $gene = array(
    'type' => 'gene',
    'name' => $t('Gene'),
    'base' => 'node_content',
    'description' => $t('The Gene content type.'),
    'body_label' => $t('Description')
  );

  $content_type = node_type_set_defaults($gene);
  node_add_body_field($content_type);
  node_type_save($content_type);

  $body_instance = field_info_instance('node', 'body', 'gene');
  $body_instance['type'] = 'text_long';
  $body_instance['label'] = 'Description';

  field_update_instance($body_instance);

  foreach (_gene_installed_fields() as $field) {
    field_create_field($field);
  }

  foreach (_gene_installed_instances() as $instance) {
    $instance['entity_type'] = 'node';
    $instance['bundle'] = $gene['type'];
    field_create_instance($instance);
  }

  variable_set('comment_gene', COMMENT_NODE_CLOSED);
  variable_set('node_options_gene', array('status'));
  variable_set('node_preview_gene', DRUPAL_DISABLED);
  variable_set('node_submitted_gene', FALSE);
}

function _gene_installed_fields() {
  $t = get_t();
  return array(
    'field_gene_gene_mutation' => array(
      'field_name'	=> 'field_gene_gene_mutation',
      'label'		=> $t('Gene Mutation'),
      'cardinality'	=> -1,
      'type'		=> 'node_reference',
      'settings'	=> array(
	'referenceable_types' => array(
	  'gene_mutation' => 'gene_mutation'
	)
      )
    ),
    'field_gene_uri' => array(
      'field_name'	=> 'field_gene_uri',
      'label'		=> t('URI'),
      'cardinality'	=> 1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_go' => array(
      'field_name'	=> 'field_gene_go',
      'label'		=> t('Gene Ontology ID'),
      'cardinality'	=> 1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_mesh' => array(
      'field_name'	=> 'field_gene_mesh',
      'label'		=> t('MeSH term'),
      'cardinality'	=> -1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_umlscui' => array(
      'field_name'	=> 'field_gene_umlscui',
      'label'		=> t('UMLS CUI'),
      'cardinality'	=> -1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_refseq' => array(
      'field_name'	=> 'field_gene_refseq',
      'label'		=> t('Refseq'),
      'cardinality'	=> 1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_uniprot' => array(
      'field_name'	=> 'field_gene_uniprot',
      'label'		=> t('Uniprot ID'),
      'cardinality'	=> -1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_entrezgene' => array(
      'field_name'	=> 'field_gene_entrezgene',
      'label'		=> t('Entrez Gene ID'),
      'cardinality'	=> -1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_accession' => array(
      'field_name'	=> 'field_gene_accession',
      'label'		=> t('Accession number'),
      'cardinality'	=> -1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_omim' => array(
      'field_name'	=> 'field_gene_omim',
      'label'		=> t('OMIM'),
      'cardinality'	=> -1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_locus' => array(
      'field_name'	=> 'field_gene_locus',
      'label'		=> t('Locus'),
      'cardinality'	=> 1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
    'field_gene_synonym' => array(
      'field_name'	=> 'field_gene_synonym',
      'label'		=> t('Synonym'),
      'cardinality'	=> -1,
      'type'		=> 'text',
      'settings'	=> array(
        'max_length' => 500,
      )
    ),
  );
}

function _gene_installed_instances() {
  $t = get_t();
  return array(
    'field_gene_gene_mutation' => array(
      'field_name'	=> 'field_gene_gene_mutation',
      'label'		=> $t('Gene Mutation'),
      'cardinality'	=> -1,
      'widget'		=> array(
        'type'    => 'node_reference_autocomplete',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_uri' => array(
      'field_name' => 'field_gene_uri',
      'label'       => $t('URI'),
      'cardinality' => 1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_go' => array(
      'field_name' => 'field_gene_go',
      'label'       => $t('Gene Ontology ID'),
      'cardinality' => 1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_umlscui' => array(
      'field_name' => 'field_gene_umlscui',
      'label'       => $t('UMLS CUI'),
      'cardinality' => -1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_accession' => array(
      'field_name' => 'field_gene_accession',
      'label'       => $t('Accession number'),
      'cardinality' => -1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_entrezgene' => array(
      'field_name' => 'field_gene_entrezgene',
      'label'       => $t('Entrez Gene ID'),
      'cardinality' => -1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_mesh' => array(
      'field_name' => 'field_gene_mesh',
      'label'       => $t('MeSH term'),
      'cardinality' => -1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_refseq' => array(
      'field_name' => 'field_gene_refseq',
      'label'       => $t('Refseq'),
      'cardinality' => 1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_uniprot' => array(
      'field_name' => 'field_gene_uniprot',
      'label'       => $t('Uniprot ID'),
      'cardinality' => -1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_omim' => array(
      'field_name' => 'field_gene_omim',
      'label'       => $t('OMIM'),
      'cardinality' => -1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_locus' => array(
      'field_name' => 'field_gene_locus',
      'label'       => $t('Locus'),
      'cardinality' => 1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
    'field_gene_synonym' => array(
      'field_name' => 'field_gene_synonym',
      'label'       => $t('Synonym'),
      'cardinality' => -1,
      'widget'      => array(
        'type'    => 'text_textfield',
      ),
      'display' => array(
	'default' => array(
	  'type'  => 'hidden',
	  'label' => 'hidden',
	),
        'full' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
        'teaser' => array(
          'type' => 'hidden',
          'label' => 'hidden',
        ),
      )
    ),
  );
}

function gene_uninstall() {
  $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
  $result = db_query($sql, array(':type' => 'gene'));
  $nids = array();
  foreach ($result as $row) {
    $nids[] = $row->nid;
  }

  node_delete_multiple($nids);

  foreach (array_keys(_gene_installed_fields()) as $field) {
    field_delete_field($field);
  }

  $instances = field_info_instances('node', 'gene');
  foreach ($instances as $instance_name => $instance) {
    field_delete_instance($instance);
  }

  node_type_delete('gene');

  field_purge_batch(1000);
}
