<?php
// $Id: x_ray.module $

function x_ray_form_x_ray_node_form_alter(&$form, &$form_state, $form_id) {
if (isset($form['type']) && isset($form['#node'])) {
    if ('x_ray_node_form' == $form_id) {
      $form['field_xray_xraycollection']['#access'] = FALSE;
    }
  }
}

function x_ray_node_view($node, $view_mode) {
  if ($node->type == 'x_ray' && $view_mode == 'full' && node_is_page($node)) {
    drupal_goto('media-gallery/detail/' . $node->field_xray_xraycollection['und'][0]['nid'] . '/'. $node->field_xray_media['und'][0]['fid']);
  }  

  return $node;
}

function x_ray_node_delete($node) {
  if ($node->type == 'x_ray') {
    if (array_key_exists('und', $node->field_xray_xraydescription)) {
      foreach ($node->field_xray_xraydescription['und'] as $desc) {
	node_delete($desc['nid']);
      }
    }
  }
}